sequenceDiagram
%% Checksum
participant SAFT
participant CryptoSAFT
Note over SAFT: checksum(1)
SAFT ->> CryptoSAFT: Symmetric Encryption - aes-128-ctr
CryptoSAFT ->> SAFT: Symmetric Decryption - aes-128-ctr
Note over SAFT: checksum(2) = checksum(1)
					